"""Regenerate the manual's reference pages from the code (backlog 0288).

The manual under ``docs/manual`` splits into hand-written narrative (concepts,
journeys) and machine-generated reference. This script owns the generated half so
it can never drift from the code: it introspects the live Typer command tree, the
``lake.*`` namespace objects, and the canonical ``TABLE_SCHEMAS`` and rewrites the
``docs/manual/reference/*.generated.md`` pages. ``tests/test_docs_reference_current.py``
re-renders in-memory and fails if the checked-in pages are stale, so a task that
changes a CLI command, a public ``lake.*`` method, or a table cannot ship without
regenerating. Run from the repo root:

    python scripts/gen_docs_reference.py

The three ``render_*`` functions are pure (string in -> string out) so the drift
test can call them without touching disk.
"""

from __future__ import annotations

import inspect
import tempfile
from pathlib import Path

import click
import typer

from lancedb_robotics.cli import app
from lancedb_robotics.lake import Lake
from lancedb_robotics.schemas import SCHEMA_VERSIONS, TABLE_SCHEMAS

ROOT = Path(__file__).resolve().parents[1]
REFERENCE_DIR = ROOT / "docs" / "manual" / "reference"

_BANNER = (
    "<!-- GENERATED by scripts/gen_docs_reference.py -- do not edit by hand.\n"
    "     Regenerate with: python scripts/gen_docs_reference.py -->\n"
)


def _first_line(text: str | None) -> str:
    if not text:
        return ""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


# --- CLI reference ----------------------------------------------------------


def render_cli() -> str:
    root = typer.main.get_command(app)
    lines = [
        _BANNER,
        "# CLI reference",
        "",
        "Every `lancedb-robotics` command group and subcommand, generated from the "
        "Typer application. Invoke as `lancedb-robotics <group> <command> [options]`.",
        "",
    ]
    groups = getattr(root, "commands", {})
    for group_name in sorted(groups):
        group = groups[group_name]
        lines.append(f"## `{group_name}`")
        help_text = _first_line(getattr(group, "help", ""))
        if help_text:
            lines.append("")
            lines.append(help_text)
        subcommands = getattr(group, "commands", None)
        if not subcommands:
            lines.append("")
            continue
        for cmd_name in sorted(subcommands):
            command = subcommands[cmd_name]
            lines.append("")
            lines.append(f"### `{group_name} {cmd_name}`")
            cmd_help = _first_line(getattr(command, "help", ""))
            if cmd_help:
                lines.append("")
                lines.append(cmd_help)
            arguments: list[str] = []
            options: list[str] = []
            for param in getattr(command, "params", []):
                param_help = _first_line(getattr(param, "help", ""))
                if isinstance(param, click.Argument):
                    label = (param.opts[0] if param.opts else param.name).upper()
                    arguments.append(f"  - `{label}`{f' — {param_help}' if param_help else ''}")
                elif isinstance(param, click.Option):
                    flags = " / ".join(param.opts)
                    tag = " (required)" if param.required else ""
                    options.append(f"  - `{flags}`{tag}{f' — {param_help}' if param_help else ''}")
            if arguments:
                lines.append("")
                lines.append("- Arguments:")
                lines.extend(arguments)
            if options:
                lines.append("")
                lines.append("- Options:")
                lines.extend(options)
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


# --- Python API reference ---------------------------------------------------


def _namespace_classes() -> list[tuple[str, type]]:
    """Map each ``lake.<name>`` accessor to its class, deduped, sorted by name.

    Aliases that return the same class (e.g. ``eval`` / ``evaluation``) collapse to
    the first accessor name so the reference lists each namespace once.
    """

    accessors = sorted(
        name
        for name, value in inspect.getmembers(Lake, lambda obj: isinstance(obj, property))
    )
    with tempfile.TemporaryDirectory() as tmp:
        lake = Lake.init(Path(tmp) / "reference.lance")
        by_class: dict[type, str] = {}
        for name in accessors:
            try:
                obj = getattr(lake, name)
            except Exception:  # noqa: BLE001 - a namespace that needs live data is skipped
                continue
            cls = type(obj)
            by_class.setdefault(cls, name)
    return sorted(((accessor, cls) for cls, accessor in by_class.items()), key=lambda item: item[0])


def render_api() -> str:
    lines = [
        _BANNER,
        "# Python API reference (`lake.*`)",
        "",
        "Public methods on each `lake.<namespace>` accessor, generated by introspecting "
        "the namespace classes. Open a lake with `Lake.open(uri)` (or `Lake.init(uri)`), "
        "then reach a namespace as `lake.<namespace>`.",
        "",
    ]
    for accessor, cls in _namespace_classes():
        lines.append(f"## `lake.{accessor}` — `{cls.__name__}`")
        class_doc = _first_line(cls.__doc__)
        if class_doc:
            lines.append("")
            lines.append(class_doc)
        lines.append("")
        methods = sorted(
            name
            for name, _ in inspect.getmembers(cls, inspect.isfunction)
            if not name.startswith("_")
        )
        for method_name in methods:
            func = getattr(cls, method_name)
            try:
                signature = str(inspect.signature(func))
            except (TypeError, ValueError):
                signature = "(...)"
            signature = signature.replace("(self, ", "(").replace("(self)", "()")
            doc = _first_line(func.__doc__)
            suffix = f" — {doc}" if doc else ""
            lines.append(f"- `{accessor}.{method_name}{signature}`{suffix}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


# --- Canonical tables reference ---------------------------------------------


def render_tables() -> str:
    lines = [
        _BANNER,
        f"# Canonical tables ({len(TABLE_SCHEMAS)})",
        "",
        "Every canonical table a lake creates on `Lake.init`, in creation order, "
        "generated from `TABLE_SCHEMAS`.",
        "",
    ]
    for table_name, schema in TABLE_SCHEMAS.items():
        version = SCHEMA_VERSIONS.get(table_name, "?")
        lines.append(f"## `{table_name}` (schema v{version})")
        lines.append("")
        lines.append("| column | type |")
        lines.append("| --- | --- |")
        for field in schema:
            lines.append(f"| `{field.name}` | `{field.type}` |")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


# --- Enterprise training compatibility matrix -------------------------------


def render_enterprise_compatibility() -> str:
    """Render the deterministic Enterprise-training compatibility matrix (0116).

    Sourced from the production backend resolver via
    ``enterprise_conformance.compatibility_matrix``, so it stays in lockstep with
    capability negotiation and fallback behavior.
    """

    from lancedb_robotics.enterprise_conformance import compatibility_matrix

    return _BANNER + compatibility_matrix().to_markdown().rstrip("\n") + "\n"


GENERATED_FILES = {
    "cli.generated.md": render_cli,
    "api.generated.md": render_api,
    "tables.generated.md": render_tables,
    "enterprise-training-compatibility.generated.md": render_enterprise_compatibility,
}


def main() -> None:
    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    for filename, render in GENERATED_FILES.items():
        (REFERENCE_DIR / filename).write_text(render(), encoding="utf-8")
        print(f"wrote docs/manual/reference/{filename}")


if __name__ == "__main__":
    main()
